universe = vanilla
executable = /home/slaing/modded-nanogpt/download.sh

LOGS_DIR = "/lustre/home/slaing/modded-nanogpt/logs"

# logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Resource requirements for download (no GPU needed)
request_cpus = 8
request_memory = 16GB

# Environment setup
initialdir = /home/slaing/modded-nanogpt
transfer_executable = False

queue 1